#!/usr/bin/env python3
"""Generate world_files.txt - the declared server-world file set (plan.md Phase 3).

The rules below define which client-project files the authoritative Godot world
needs to boot `scenes/server/dedicated_server.tscn`. Regenerating is
deterministic; the export tool copies exactly this list and hash-pins it into
server/world/WORLD_EXPORT.json.

Usage: python gen_world_files.py --client <client repo root> [--check]
  --check  verify the existing world_files.txt matches the rules (exit 1 on drift)
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "world_files.txt")

EXCLUDE_SCRIPTS_DIRS = ("scripts/test/",)
# Content families the authoritative world loads: models with their next-to-file
# textures, the shaders they use and the PBR sets the map builders sample.
ASSET_FAMILIES = (
    ("assets/models/characters", (".glb", ".gltf", ".png")),
    ("assets/models/monsters", (".glb", ".gltf", ".png")),
    ("assets/models/environment", (".glb", ".gltf", ".png")),
    ("assets/models/gothic_kit", (".glb", ".gltf", ".png")),
    ("assets/models/props", (".glb", ".gltf", ".png")),
    ("assets/shaders", (".gdshader",)),
    ("assets/textures/pbr", (".png", ".jpg", ".exr")),
    # Phase 12: the effect atlases AND their authored meshes - the world
    # instantiates shield/projectile/trail layers too.
    ("assets/vfx", (".png", ".glb")),
)
# Owned by server/world/addons/hpmmo_sim/data/ since Phase 5; the client copy is
# generated by dev.ps1 sync-sim.
SERVER_OWNED_DATA = ("spells.json", "safe_zones.json")


def build(client):
    files = ["project.godot"]
    for root, dirs, names in os.walk(os.path.join(client, "scripts")):
        dirs[:] = [d for d in dirs if d != ".godot"]
        for n in sorted(names):
            if not n.endswith(".gd"):
                continue
            rel = os.path.relpath(os.path.join(root, n), client).replace("\\", "/")
            if any(rel.startswith(x) for x in EXCLUDE_SCRIPTS_DIRS):
                continue
            files.append(rel)
    # Scenes needed by the world: server boot, world, entities, spells, and the
    # UI scenes that gameplay scripts/scenes hard-preload (floating text, HUD,
    # inventory, ollivander) so parsing succeeds even though the dedicated
    # server frees the CanvasLayer at startup.
    for sub in ("scenes/server", "scenes/world", "scenes/entities", "scenes/spells", "scenes/ui"):
        for root, dirs, names in os.walk(os.path.join(client, sub)):
            for n in sorted(names):
                if n.endswith(".tscn"):
                    rel = os.path.relpath(os.path.join(root, n), client).replace("\\", "/")
                    files.append(rel)
    # Client-owned content data. The gameplay contracts (spells, safe zones)
    # moved to the server-owned simulation package in Phase 5 and are preserved
    # under world/addons/hpmmo_sim/, so they are not exported from here.
    for n in sorted(os.listdir(os.path.join(client, "data", "json"))):
        if n.endswith(".json") and n not in SERVER_OWNED_DATA:
            files.append("data/json/" + n)
    # Assets the reachable scenes/scripts load: player + monster models, the
    # modular environment pieces referenced by game_world.tscn, the masonry
    # shader, and the two particle stills used by ParticleKit.
    # Phase 12: the sound library manifest (a few KB) travels with the world so
    # the AudioManager's keys resolve on the server too; the WAVs themselves do
    # not (there is no audio device in a dedicated server).
    library = os.path.join(client, "assets", "audio", "sound_library.json")
    if os.path.exists(library):
        files.append("assets/audio/sound_library.json")
    files.append("assets/models/characters/wizard.glb")
    for root, dirs, names in os.walk(os.path.join(client, "assets", "models", "monsters")):
        for n in sorted(names):
            if n.endswith((".gltf", ".glb")):
                files.append(os.path.relpath(os.path.join(root, n), client).replace("\\", "/"))
    for root, dirs, names in os.walk(os.path.join(client, "assets", "models", "environment")):
        for n in sorted(names):
            if n.endswith((".gltf", ".glb")):
                files.append(os.path.relpath(os.path.join(root, n), client).replace("\\", "/"))
    # Asset families the exported world's scenes and scripts load at runtime:
    # the player/broom models the world instantiates for every connected body,
    # the Gothic kit + PBR sets the terrain, castle and interior builders place
    # (so the server's authoritative geometry matches the client's), and the
    # shaders/materials those use. Textures next to a model belong to it.
    for sub, exts in ASSET_FAMILIES:
        for root, dirs, names in os.walk(os.path.join(client, sub)):
            dirs[:] = [d for d in dirs if d != ".godot"]
            for n in sorted(names):
                if n.endswith(exts):
                    files.append(os.path.relpath(os.path.join(root, n), client).replace("\\", "/"))
    files.append("assets/textures/masonry.gdshader")
    files.append("assets/vfx/flame_01.png")
    files.append("assets/vfx/spark_01.png")
    return sorted(set(files))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--client", required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    wanted = build(args.client)
    body = "# Generated by gen_world_files.py - server world file set (do not edit by hand).\n"
    body += "\n".join(wanted) + "\n"
    if args.check:
        current = ""
        if os.path.exists(OUT):
            current = open(OUT, encoding="utf-8").read()
        if current != body:
            print("world_files.txt drift detected; run gen_world_files.py to refresh")
            return 1
        print(f"world_files.txt OK ({len(wanted)} files)")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print(f"wrote {OUT}: {len(wanted)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
